# Generated by Django 3.1.4 on 2021-01-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeds',
            name='owner',
        ),
    ]
