# Generated by Django 3.1.4 on 2021-05-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_feeds_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='image',
            field=models.ImageField(null=True, upload_to='front_end/public/image/feeds/'),
        ),
    ]
