# Generated by Django 3.1.4 on 2021-01-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0003_auto_20210105_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
