# Generated by Django 3.1.4 on 2021-01-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0004_auto_20210105_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickName',
            field=models.CharField(max_length=255),
        ),
    ]
