# Generated by Django 3.1.4 on 2021-01-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0007_auto_20210105_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickName',
            new_name='nickname',
        ),
    ]
