# Generated by Django 3.1.4 on 2021-01-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0009_auto_20210107_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(null=True, upload_to='front_end/public/image/profile/'),
        ),
    ]
